import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PresenceContext from "./context/PresenceContext";
import AuthContext from "./context/AuthContext";
import ToasterContext from "./context/ToasterContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Messenger Clone",
  description: "Generated by create next app",
};

/**
 * This component handles the layout of the app.
 * 
 * It allows React Toaster to be accessed globally using `ToasterContext`.
 * 
 * It allows NextAuth sessions to be accessed globally using `AuthContext`.
 * 
 * It allows Pusher's active channels to be accessed globally using `ActiveStatus`.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterContext />
        <AuthContext>
          <PresenceContext />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
